# Generated by Django 3.2.3 on 2021-06-07 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_alter_register_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_name', models.CharField(max_length=50)),
                ('domain', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='comp_details',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comp_info', to='job.company'),
            preserve_default=False,
        ),
    ]
