# Generated by Django 3.2.3 on 2021-06-07 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_alter_employee_comp_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='comp_details',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp_info', to='job.company'),
        ),
    ]
