# Generated by Django 3.2.3 on 2021-06-07 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_alter_employee_comp_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='comp_details',
        ),
    ]
