# Generated by Django 3.2.3 on 2021-06-07 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_remove_employee_comp_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
