# Generated by Django 3.2.3 on 2021-06-07 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_auto_20210607_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='comp_details',
        ),
        migrations.AddField(
            model_name='register',
            name='comp_details',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='comp_info', to='job.company'),
            preserve_default=False,
        ),
    ]
